include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - windows/**
  errors:
    deprecated_member_use: ignore
    prefer_initializing_formals: ignore
    unnecessary_underscores: ignore
    curly_braces_in_flow_control_structures: ignore
