<?php

declare(strict_types=1);

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

/**
 * Sent to a user when an admin triggers a password reset on their behalf.
 *
 * The user receives a secure, time-limited reset link (generated by Laravel's
 * password broker). The admin never sees or sets the new password — the user
 * sets it themselves via the reset form.
 */
class AdminPasswordResetNotification extends Notification
{
    use Queueable;

    public function __construct(
        private readonly string $resetUrl,
        private readonly string $adminName,
    ) {}

    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        return (new MailMessage)
            ->subject('Password Reset Request — Npontu Support Tracker')
            ->greeting('Hello, '.$notifiable->name.'!')
            ->line('**'.$this->adminName.'** (Administrator) has requested a password reset for your account on the Npontu Technologies Support Activity Tracker.')
            ->action('Reset My Password', $this->resetUrl)
            ->line('This reset link will expire in **60 minutes**.')
            ->line('If you did not request this reset or believe this is an error, you can safely ignore this email — your password will not change.')
            ->line('> 🔒 For your security, never share this link with anyone.')
            ->salutation('— Npontu Technologies Support Team');
    }
}
